// ------------------------------
// Font Awesome Icons
// ------------------------------
import {
  FaLinkedin,
  FaTwitter,
  FaInstagram,
  FaFacebookF,
  FaUser as FaUserIcon // ✅ Font Awesome version
} from "react-icons/fa";

// ------------------------------
// Lucide Icons
// ------------------------------
import {
  Menu as FaBars,
  X as FaTimes,
  Zap as FaBolt,
  Map as FaMapMarkedAlt,
  Shield as FaShieldAlt,
  MapPin as FaMapMarkerAlt,
  Phone as FaPhoneAlt,
  Mail as FaEnvelope,
  Clock as FaClock,
  Home as FaHome,
  Info as FaInfoCircle,
  UserPlus as FaUserPlus,
  Contact as FaAddressBook,
  Settings as FaCog,
  Plus as FaPlus,
  Gauge as FaTachometerAlt,
  Users as FaUsers,
  ClipboardList as FaClipboardList,
  LineChart as FaChartLine,
  Store as FaStore,
  Boxes as FaBoxes,
  Truck as FaTruck,
  BarChart as FaChartBar,
  List as FaListAlt,
  ClipboardCheck as FaClipboardCheck,
  Wallet as FaMoneyBillWave,
  Star as FaStar,
  Quote as FaQuoteLeft,
  Camera as FaCamera,
  UploadCloud as FaCloudUploadAlt,
  User as LucideUser, // ✅ Lucide version
  Send as FaPaperPlane,
  Check as FaCheck,
  IndianRupee as FaRupeeSign,
  Settings2 as FaUserCog,
  LogOut as FaSignOutAlt,
  PenLine as FaPen,
  UserCircle as FaUserCircle,
  Package,
  ShoppingBag,
  ShoppingCart,
  MapPin,
  Clock,
  Eye,
  X,
  Truck,
  CreditCard,
  CheckCircle,
  Search,
  Filter,
  Calendar,
  Scale,
  Tag,
  MessageSquare,
  Phone,
  Store,
  Mail,
  AlertCircle,
  RefreshCw,
  LockIcon
  
} from "lucide-react";

export const Icons = {
  // 👉 Font Awesome Icons
  FaLinkedin,
  FaTwitter,
  FaInstagram,
  FaFacebookF,
  FaUserIcon, // Font Awesome User

  // 👉 Lucide Icons (aliased as Fa* to match style)
  FaBars,
  FaTimes,
  FaBolt,
  FaMapMarkedAlt,
  FaShieldAlt,
  FaMapMarkerAlt,
  FaPhoneAlt,
  FaEnvelope,
  FaClock,
  FaHome,
  FaInfoCircle,
  FaUserPlus,
  FaAddressBook,
  FaCog,
  FaPlus,
  FaTachometerAlt,
  FaUsers,
  FaClipboardList,
  FaChartLine,
  FaStore,
  FaBoxes,
  FaTruck,
  FaChartBar,
  FaListAlt,
  FaClipboardCheck,
  FaMoneyBillWave,
  FaStar,
  FaQuoteLeft,
  FaCamera,
  FaCloudUploadAlt,
  FaPaperPlane,
  FaCheck,
  FaRupeeSign,
  FaUserCog,
  FaSignOutAlt,

  // Lucide Native Icons
  LucideUser, // Lucide's User icon (distinct from FaUserIcon)
  Package,
  ShoppingBag,
  ShoppingCart,
  MapPin,
  Clock,
  Eye,
  X,
  Truck,
  CreditCard,
  CheckCircle,
  Search,
  Filter,
  Calendar,
  Scale,
  Tag,
  MessageSquare,
  Phone,
  Store,
  Mail,
  AlertCircle,
  RefreshCw,
  FaPen,
  FaUserCircle,
  LockIcon
};
