import {
  Menu as FaBars,
  X as FaTimes,
  Zap as FaBolt,
  Map as FaMapMarkedAlt,
  Shield as FaShieldAlt,
  MapPin as FaMapMarkerAlt,
  Phone as FaPhoneAlt,
  Mail as FaEnvelope,
  Clock as FaClock,
  Linkedin as FaLinkedin,
  Twitter as FaTwitter,
  Instagram as FaInstagram,
  Facebook as FaFacebookF,
  Home as FaHome,
  Info as FaInfoCircle,
  UserPlus as FaUserPlus,
  Contact as FaAddressBook,
  Settings as FaCog,
  Plus as FaPlus,
  Gauge as FaTachometerAlt,
  Users as FaUsers,
  ClipboardList as FaClipboardList,
  LineChart as FaChartLine,
  Store as FaStore,
  Boxes as FaBoxes,
  Truck as FaTruck,
  BarChart as FaChartBar,
  List as FaListAlt,
  ClipboardCheck as FaClipboardCheck,
  Wallet as FaMoneyBillWave,
  Star as FaStar,
  Quote as FaQuoteLeft,
  Camera as FaCamera,
  UploadCloud as FaCloudUploadAlt,
  User as FaUser,
  Send as FaPaperPlane,
  Check as FaCheck,
  IndianRupee as FaRupeeSign,
  Package,
  ShoppingBag,
  ShoppingCart,
  MapPin,
  Clock,
  Eye,
  X,
  Truck,
  CreditCard,
  CheckCircle,
  Search,
  Filter,
  Calendar,
  Scale, 
  Tag, 
  MessageSquare, 
  User, 
  Phone,  
  Store, 
  Mail, 
  AlertCircle,
  RefreshCw,
} from "lucide-react";

export const Icons = {
  FaBars,
  FaTimes,
  FaBolt,
  FaMapMarkedAlt,
  FaShieldAlt,
  FaMapMarkerAlt,
  FaPhoneAlt,
  FaEnvelope,
  FaClock,
  FaLinkedin,
  FaTwitter,
  FaInstagram,
  FaFacebookF,
  FaHome,
  FaInfoCircle,
  FaUserPlus,
  FaAddressBook,
  FaCog,
  FaPlus,
  FaTachometerAlt,
  FaUsers,
  FaClipboardList,
  FaChartLine,
  FaStore,
  FaBoxes,
  FaTruck,
  FaChartBar,
  FaListAlt,
  FaClipboardCheck,
  FaMoneyBillWave,
  FaStar,
  FaQuoteLeft,
  FaCamera,
  FaCloudUploadAlt,
  FaUser,
  FaPaperPlane,
  FaCheck,
  FaRupeeSign,
  Package,
  ShoppingBag,
  ShoppingCart,
  MapPin,
  Clock,
  Eye,
  X,
  Truck,
  CreditCard,
  CheckCircle,
  Search,
  Filter,
  Calendar,
  Scale, 
  Tag, 
  MessageSquare, 
  User, 
  Phone,  
  Store, 
  Mail, 
  AlertCircle,
  RefreshCw
};
